# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-12 14:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_category_page'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('userid', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
    ]
