# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-30 14:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_plist'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Plist',
            new_name='Playlist',
        ),
    ]
