# Generated by Django 2.0.4 on 2018-05-09 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0007_remove_song_is_favourite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='category',
        ),
        migrations.DeleteModel(
            name='Users',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Page',
        ),
    ]
